services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: basic-app
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - '5432:5432'
